apiVersion: v1
kind: Secret
metadata:
  name: urna-secret
  namespace: urna-eletronica
  labels:
    app.kubernetes.io/name: urna-eletronica
type: Opaque
stringData:
  DB_USER: "urna"
  DB_PASS: "urna123"
  MYSQL_ROOT_PASSWORD: "rootpassword"
