apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: urna-db-pvc
  namespace: urna-eletronica
  labels:
    app.kubernetes.io/name: urna-eletronica
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
